wip: API calls resulting in no data will not be dispatched
btpworks/chronicle pull request #213
Opened 2023-03-02 20:54 UTC by suchapalaver

- Provides an API response to indicate that the data is already there

---
[CHRON-146](https://blockchaintp.atlassian.net/browse/CHRON-146)

Signed-off-by: Joseph Livesey [joseph.livesey@btp.works](mailto:joseph.livesey@btp.works)

2023-03-06 15:42 UTC, mtbc commented on crates/api/src/lib.rs
> +    #[error("Json LD processing: {0}")]
```suggestion
    #[error("JSON-LD processing: {0}")]
```
(may as well fix it if adjusting the line anyway)

2023-03-09 18:44 UTC, ryanbtp requested changes

2023-03-09 18:44 UTC, ryanbtp commented on crates/api/src/chronicle_graphql/mod.rs
> +    Null,
Not sure I like Null. NoOperation or AlreadyRecorded?

2023-03-10 10:32 UTC, ryanbtp approved these changes

2023-03-10 13:53 UTC, merged