docs(upgrading): update version upgrade summary
btpworks/chronicle pull request #262
Opened 2023-04-17 15:22 UTC by suchapalaver

Bringing `upgrading.md` up to date.

[CHRON-296](https://blockchaintp.atlassian.net/browse/CHRON-296)

Signed-off-by: Joseph Livesey [joseph.livesey@btp.works](mailto:joseph.livesey@btp.works)

2023-04-17 15:44 UTC, mtbc commented on docs/upgrading.md
> +not authorized via Auth0, allowing for the option to pass a transactor key as a CLI
No need to mention Auth0 specifically, deployments may be using other providers.

2023-04-17 15:47 UTC, mtbc commented on docs/upgrading.md
> +<http://localhost:9982/data/chronicle:agent:my-agent-id> and see a JSON summary.
also for entity and activity

2023-04-17 15:51 UTC, mtbc commented on docs/upgrading.md
> +  dereferencing a JWT structure
```suggestion
- an agent along with its corresponding key pair
- a pointer into a JWT structure, for retrieving the external id to use for the agent and its key pair.
```

2023-04-17 19:06 UTC, ryanbtp requested changes

2023-04-17 19:06 UTC, ryanbtp commented on docs/upgrading.md
> +Chronicle integrates OPA execution at its GraphQL API request point and in its Transaction
endpoint

2023-04-17 19:06 UTC, ryanbtp commented on docs/upgrading.md
> +performance for large-scale data management.
As an aside this is noticeable with the ETL on the discover project that's using a fake ledger. Chronicle is blessed performance wise as it is almost certainly dependent on something a lot slower than it so is always going to look good.

2023-04-18 14:26 UTC, ryanbtp approved these changes

2023-04-18 15:47 UTC, merged