fix: complete documenting opactl cli commands
btpworks/chronicle pull request #264
Opened 2023-04-18 13:28 UTC by suchapalaver

Completes [CHRON-291](https://blockchaintp.atlassian.net/browse/CHRON-291).

Signed-off-by: Joseph Livesey [joseph.livesey@btp.works](mailto:joseph.livesey@btp.works)

2023-04-18 13:50 UTC, mtbc approved these changes

2023-04-18 14:26 UTC, ryanbtp requested changes

2023-04-18 14:26 UTC, ryanbtp commented on docs/opa.md
> +- `--policy` (`-p`): A required argument that specifies the path of the policy.
path to?

2023-04-19 16:18 UTC, ryanbtp approved these changes

2023-04-19 17:10 UTC, merged