describe how to record changes without contradiction
btpworks/chronicle pull request #359
Opened 2023-06-16 11:30 UTC by mtbc

Resolves CHRON-377 by explaining how to work with immutability.

# PR Checklist

## Please complete this checklist after opening your PR

* [ ] I have updated documentation as necessary
* [ ] I have updated helm chart(s) if needed
* [ ] I have added tests if needed
* [ ] All new and existing tests are passing
* [ ] Any breaking changes are clearly flagged and documented
* [ ] I’ve included a link to any relevant ticket(s)

2023-06-16 13:19 UTC, ryanbtp requested changes

2023-06-16 13:19 UTC, ryanbtp commented on docs/recording_provenance.md
> +the value set for every attribute remains constant. If one chooses to take
probably don't need 'set'

2023-06-16 13:19 UTC, ryanbtp commented on docs/recording_provenance.md
> +locations, and illustrate other facets of modeling domains in Chronicle.
Possibly say something explicit about having to model changes to attributes as provenance?

2023-06-19 19:12 UTC, suchapalaver requested changes

2023-06-19 19:12 UTC, suchapalaver commented on docs/recording_provenance.md
> +entities in their own right. Then, for example, an person could engage in the
```suggestion
entities in their own right. Then, for example, a person could engage in the
```

2023-06-19 19:12 UTC, suchapalaver commented on docs/recording_provenance.md
> +be an entity derived from the artifact. An agent can engage in the activities
```suggestion
be an entity derived from the artifact itself. An agent can engage in the activities
```

2023-06-19 21:30 UTC, ryanbtp approved these changes

2023-06-20 10:14 UTC, suchapalaver approved these changes

2023-06-20 10:14 UTC, merged